version: "3"
services:
  mongo:
    image: mongo
    ports:
    - "27019:27017"
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo
  mongo-seed2:
    build: ./mongo-seed2
    links:
      - mongo
  mongo-seed3:
    build: ./mongo-seed3
    links:
      - mongo
  web:
    restart: always
    build: ./unoabcd
    ports:
    - "8091:3000"
    links:
      - mongo
